### ISSUE TITLE
Verbose "-v" flag in v20-trade-get does not work

### ISSUE THREAD

**Issue by night00** [oanda/v20-python#17]
Steps to reproduce:
1) Open a position, for example:
v20-order-market --tp 1.07257 --sl 1.07057 EUR/USD 1000
2) List trades:
v20-trade-get --all

Trade 50: 1000.0 (1000.0) of EUR_USD @ 1.07166

3) List with "-v" flag:
v20-trade-get -v --all
--------------------------------------------------------------------------------
Traceback (most recent call last):
```
  File "[...]/v20-python-samples-master/env/bin/v20-trade-get", line 11, in <module>
    load_entry_point('v20-python-samples', 'console_scripts', 'v20-trade-get')()
  File "[...]//v20-python-samples-master/src/trade/get.py", line 73, in main
    print(trade.yaml(True))
AttributeError: 'Trade' object has no attribute 'yaml'
```

The code seems to call a non-existent trade.yaml.
In a differente file instead (view.py, same directory) the same result seems to be obtained in a different way:
```
    common.view.print_collection(
        "{} Trades".format(len(trades)),
        trades,
        [
            ("ID", lambda t: t.id),
            ("State", lambda t: t.state),
            ("Summary", lambda t: t.summary()),
            ("Unrealized P/L", lambda t: t.unrealizedPL),
            ("P/L", lambda t: t.realizedPL)
        ]
    )
```

Thank you

**Comment by night00** [comment]
This little patch implements the same code and corrects the bug for the "all" part:

```
--- get.py.orig 2017-01-19 10:15:06.204750140 +0100
+++ get.py      2017-01-19 10:33:30.239029813 +0100
@@ -66,13 +66,23 @@
         if not args.summary:
             print("-" * 80)
 
-        for trade in reversed(response.get("trades", 200)):
-            if args.summary:
+        if args.summary:
+            for trade in reversed(response.get("trades", 200)):
                 print(trade.title())
-            else:
-                print(trade.yaml(True))
-                print("-" * 80)
-        
+        else:
+            trades=response.get("trades", 200)
+            common.view.print_collection(
+                "{} Trades".format(len(trades)),
+                trades,
+                [
+                    ("ID", lambda t: t.id),
+                    ("State", lambda t: t.state),
+                    ("Summary", lambda t: t.summary()),
+                    ("Unrealized P/L", lambda t: t.unrealizedPL),
+                    ("P/L", lambda t: t.realizedPL)
+                ]
+            )
+            print("-" * 80)
         return
 
     if args.trade_id:

```

As you can see, I had to reverse the logic of the "if" and I moved the "for" block inside the if block.

**Comment by dmpettyp** [comment]
Hmm. Looks like an experimental feature I was working on last year in the python bindings crept through into the sample code but I didn't end up pushing the feature. I'll cut a 3.0.14 release soon that should fix this.

**Comment by dmpettyp** [comment]
I have pushed out v20 python 3.0.14 and updated the sample repository to use it. please recreate your virtualenv and everything should work.
